chrome:
  defaultVersion: "112.0"
  path: "/"
  kernelCaps:
  - SYS_ADMIN
  spec:
    env:
    - name: ENABLE_VNC
      value: 'true'
    resources:
      requests:
        cpu: '1'
        memory: 1.5Gi
      limits:
        cpu: '1.5'
        memory: 2Gi
  versions:
    '112.0':
      image: selenoid/vnc_chrome:112.0
firefox:
  defaultVersion: "103.0"
  path: "/wd/hub"
  kernelCaps:
  - SYS_ADMIN
  spec:
    env:
    - name: ENABLE_VNC
      value: 'true'
    resources:
      requests:
        cpu: '1'
        memory: 1.5Gi
      limits:
        cpu: '1.5'
        memory: 2Gi
  versions:
    '76.0':
      image: selenoid/vnc:firefox_76.0
    '77.0':
      image: selenoid/vnc:firefox_77.0
    '78.0':
      image: selenoid/vnc:firefox_78.0
    '79.0':
      image: selenoid/vnc:firefox_79.0
    '80.0':
      image: selenoid/vnc:firefox_80.0
    '81.0':
      image: selenoid/vnc:firefox_81.0
    '82.0':
      image: selenoid/vnc:firefox_82.0
    '83.0':
      image: selenoid/vnc:firefox_83.0
    '84.0':
      image: selenoid/vnc:firefox_84.0
    '85.0':
      image: selenoid/vnc:firefox_85.0
    '86.0':
      image: selenoid/vnc:firefox_86.0
    '87.0':
      image: selenoid/vnc:firefox_87.0
    '88.0':
      image: selenoid/vnc:firefox_88.0
    '103.0':
      image: selenoid/vnc:firefox_103.0
opera:
  defaultVersion: "75.0"
  path: "/"
  kernelCaps:
  - SYS_ADMIN
  versions:
    '65.0':
      image: selenoid/vnc:opera_65.0
    '66.0':
      image: selenoid/vnc:opera_66.0
    '67.0':
      image: selenoid/vnc:opera_67.0
    '68.0':
      image: selenoid/vnc:opera_68.0
    '69.0':
      image: selenoid/vnc:opera_69.0
    '70.0':
      image: selenoid/vnc:opera_70.0
    '71.0':
      image: selenoid/vnc:opera_71.0
    '72.0':
      image: selenoid/vnc:opera_72.0
    '73.0':
      image: selenoid/vnc:opera_73.0
    '74.0':
      image: selenoid/vnc:opera_74.0
    '75.0':
      image: selenoid/vnc:opera_75.0
MicrosoftEdge:
  defaultVersion: "91.0"
  path: "/"
  kernelCaps:
  - SYS_ADMIN
  spec:
    env:
    - name: ENABLE_VNC
      value: 'true'
    resources:
      requests:
        cpu: '1'
        memory: 1.5Gi
      limits:
        cpu: '1.5'
        memory: 2Gi
  versions:
    '88.0':
      image: browsers/edge:88.0
    '89.0':
      image: browsers/edge:89.0
    '90.0':
      image: browsers/edge:90.0
    '91.0':
      image: browsers/edge:91.0
